// Lab 02 — cache-first with a precached app shell.
//
// The version comes from the script URL (?v=N) so you can "deploy" from the page.
// In a real build this is generated: a content hash of the precache manifest.

const VERSION = new URL(self.location).searchParams.get('v') || '1';
const CACHE = `shell-v${VERSION}`;

// The app shell: everything needed to render the UI with no network at all.
// In production this list is generated by the build, with fingerprinted URLs.
const PRECACHE = [
  './',
  './index.html',
  './app.js',
  '/shared/lab.css',
  '/shared/lab-ui.js',
  `/api/asset?name=shell-logo&type=svg&cc=max-age%3D3600&v=${VERSION}`,
  `/api/asset?name=shell-config&type=json&cc=max-age%3D3600&v=${VERSION}`,
];

const log = async (msg) => {
  console.log(`[sw v${VERSION}] ${msg}`);
  const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' });
  for (const c of clients) c.postMessage({ type: 'log', version: VERSION, msg });
};

// ---------------------------------------------------------------------------
// install — precache, all or nothing
// ---------------------------------------------------------------------------

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await log(`installing: precaching ${PRECACHE.length} entries into ${CACHE}`);

    // cache.addAll() is atomic-ish: if ANY request fails, the whole promise rejects and the
    // install fails, so you never end up with a half-populated shell. That is the behaviour
    // you want — but it also means one 404 in your manifest blocks every deploy, which is why
    // the manifest must be generated, never hand-written.
    try {
      await cache.addAll(PRECACHE);
      await log('precache complete');
    } catch (err) {
      await log(`PRECACHE FAILED: ${err.message} — this worker will not activate`);
      throw err;
    }
    self.skipWaiting();
  })());
});

// ---------------------------------------------------------------------------
// activate — delete the caches this version no longer owns
// ---------------------------------------------------------------------------

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    const stale = keys.filter((k) => k.startsWith('shell-v') && k !== CACHE);
    await Promise.all(stale.map((k) => caches.delete(k)));
    await log(`activated. deleted ${stale.length} old cache(s): ${stale.join(', ') || 'none'}`);
    await self.clients.claim();
  })());
});

// ---------------------------------------------------------------------------
// fetch — cache first, for things that never change at a given URL
// ---------------------------------------------------------------------------

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;                       // never cache writes

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;            // let cross-origin through

  // Anything explicitly marked as immutable-by-URL gets cache-first.
  const cacheFirst = PRECACHE.some((p) => new URL(p, self.location).href === url.href) ||
    url.searchParams.get('strategy') === 'cache-first';

  if (!cacheFirst) return;                                    // everything else: default network

  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreVary: true });
    if (cached) {
      log(`HIT  ${url.pathname}${url.search}`);
      return cached;
    }
    log(`MISS ${url.pathname}${url.search} — going to the network`);
    const res = await fetch(request);

    // Only cache successful, non-opaque responses. An opaque response (status 0) caches
    // happily and can be a 404 you will never notice — see Lab 05.
    if (res.ok && res.type !== 'opaque') {
      const cache = await caches.open(CACHE);
      cache.put(request, res.clone());
    }
    return res;
  })());
});

self.addEventListener('message', async (event) => {
  if (event.data === 'inspect') {
    const keys = await caches.keys();
    const detail = {};
    for (const k of keys) {
      const c = await caches.open(k);
      detail[k] = (await c.keys()).map((r) => r.url.replace(self.location.origin, ''));
    }
    event.source?.postMessage({ type: 'caches', detail, version: VERSION });
  }
});
